# Generated by Django 5.1.7 on 2025-03-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subject_gradetopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradetopic',
            name='topics',
            field=models.JSONField(default=list, help_text='List of topics for the grade'),
        ),
    ]
