# Generated by Django 5.1.7 on 2025-03-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='elo_amount',
            field=models.IntegerField(blank=True, help_text='Elo points for this battle', null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='grade',
            field=models.IntegerField(editable=False),
        ),
    ]
