# Generated by Django 5.1.7 on 2025-03-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_battle_elo_amount_alter_battle_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='elo_amount',
        ),
    ]
